### PR TITLE
Fixes #1090. Checks for overflowing dimensions.

### LINKED ISSUE #1090: Encoding huge BMP panics/creates corrupted file
I’m using _image 0.22.3_ with _rustc 1.39_ on 64-bit Windows 10.

```rust
let img = RgbImage::new(40_000, 40_000);
img.save_with_format("image.bmp", ImageFormat::BMP).unwrap();
```

This code panics in debug mode and creates an (assumably corrupted) file in release mode.

`thread 'main' panicked at 'attempt to multiply with overflow', bmp\encoder.rs:36:26`

The BMP format might not be able to store such a large image, but the encoder should at least return an `Err()` in both debug and release modes in such a case.

### PR DESCRIPTION
**Pull request by Mike-Neto**
Refactored for master.

### CODE REVIEW

File: src/bmp/encoder.rs [hunk 1]
```diff
@@ -33,7 +33,22 @@ impl<'a, W: Write + 'a> BMPEncoder<'a, W> {
         let (dib_header_size, written_pixel_size, palette_color_count) = get_pixel_info(c)?;
         let row_pad_size = (4 - (width * written_pixel_size) % 4) % 4; // each row must be padded to a multiple of 4 bytes
 
-        let image_size = width * height * written_pixel_size + (height * row_pad_size);
+        let image_size = width
+            .checked_mul(height)
+            .ok_or(io::Error::new(
+                io::ErrorKind::InvalidInput,
+                "Overflowing dimensions",
+            ))?
```
Comment (HeroicKatora) [inline src/bmp/encoder.rs]: Compared to the error code on the `next` branch, this performs some real work and an allocation. Providing these arguments by value means that *all* code paths, not only the erroring ones, will instantiate these three times. This should utilize a closure and `ok_or_else` instead.

```rust
let make_invalid_input_err = || io::Error::new(
    io::ErrorKind::InvalidInput,
    "Overflowing dimensions");

let image_size = width
    .checked_mul(height)
    .ok_or_else(make_invalid_input_err)?
```

Comment (Mike-Neto) [reply src/bmp/encoder.rs]: Great comment thanks. Updated as requested.
