### PR TITLE
Fix icc profile returned properly in BMPDecoder

### LINKED ISSUE #2756: Wrong bytes returned for ICC profile in BMPDecoder
During the final integration with Chromium, we detected that the returned bytes for icc profiles are shifted because it is not taking into consideration the bmp header bytes.

## Expected

icc_profile() from BMPDecoder returns exact ICC profile content

## Actual behaviour

icc_profile() is returned content shifted by 14 bytes

### PR DESCRIPTION
**Pull request by telecos**
During integration in Chromium we found that returned bytes for icc profile were shifted. The issue was not detected before because unit tests only verified that returned size of ICC profile was the expected, but it was not validating that it could properly be parsed. With this change we also improve the test to parse the profile with moxcms and do a minimal validation that it can be parsed without error.

Fixes #2756

### CODE REVIEW

File: src/codecs/bmp/decoder.rs [hunk 1]
```diff
@@ -233,15 +234,18 @@ impl ParsedIccProfile {
...
         // bV5ProfileSize is at offset 116 from header start, which is offset 112 from after size field
         let profile_size = u32::from_le_bytes(buffer[112..116].try_into().unwrap());
 
-        if profile_size == 0 || profile_offset == 0 {
+        if profile_size == 0 || profile_offset_from_header == 0 {
             return None;
         }
 
+        // Compute the absolute file offset by adding the header's position to the relative offset
+        let profile_offset = bmp_header_offset as u32 + profile_offset_from_header;
```
Comment (197g) [inline src/codecs/bmp/decoder.rs]: nit: the cast being very lossy here is smell of an inconsisteny: either the smaller offset should part of the function signature (i.e. turn `bmp_header_offset` into a `u32` and accept that we only support bmps at the start of files) or the offset should be tracked as proper `u64` stream position. Since the use is a `seek(FromStart(…))` with conversion to `u64` anyways I would heavily gravitate towards the latter.

**Review by 197g — COMMENTED** [review]
What a catch, sorry for having missed this in review apparently. I agree with the underlying issue being the test infrastructure, we can learn from this for other format's metadata support.

File: src/codecs/bmp/decoder.rs (hunk 1 above)
Comment (telecos) [reply src/codecs/bmp/decoder.rs]: Updated to work with `u64` to have clean usage of it in Seek and just converting the field from header which is `u32` to `u64`
