### PR TITLE
Fix for a wrong buffer size with an animated WEBP

### LINKED ISSUE #1856: Lossy WEBP with alpha: source slice length (761600) does not match destination slice length (997920)
Whenever I try to decode [this webp image](https://make.hmc.edu/img/equipment/cricut.webp) I get the following error:
```
panicked at 'source slice length (761600) does not match destination slice length (997920)'
C:\Users\Ethan Vazquez\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.24.5\./src\codecs\webp\extended.rs:459:21
```
image

### PR DESCRIPTION
**Pull request by arskov**
In case of an animated WEBP image, which contains frames of a smaller size than an image's canvas, the buffer of a whole image is bigger than the buffer of the first frame. This results in a panic while trying to copy a frame buffer to an image buffer. This is applicable to a case when a user wants to create an image from a file or an in memory buffer like this:

```rust
let path = "/some/path/to/animated_transparent.webp
let mut buffer = Vec::new();
let _ = std::fs::File::open(path)?.read_to_end(&mut buffer);
let img = image::load_from_memory(&buffer)?;
let size = img.dimensions();
let buffer = img.to_rgb8().into_raw();
```

This fix checks if the first frame is of a smaller size, and in this case draws a subimage to a canvas.
I have this issue in my personal case, but I believe it also fixes #1856.

I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to choose either at their option.

### CODE REVIEW

File: src/codecs/webp/extended.rs [hunk 1]
```diff
@@ -326,10 +326,27 @@ impl ExtendedImage {
...
+                    first_frame.image.fill_buf(buf);
+                } else {
+                    let bg_color = match &self.info._alpha {
+                        true => Rgba::from([0, 0, 0, 0]),
+                        false => anim_info.background_color,
+                    };
+                    let mut canvas = RgbaImage::from_pixel(canvas_width, canvas_height, bg_color);
+                    let _ = ExtendedImage::draw_subimage(&mut canvas, first_frame, bg_color)
+                        .unwrap()
+                        .unwrap();
```
Comment (fintelia) [inline src/codecs/webp/extended.rs:342]: Should we be returning an error here instead of panicking?

Comment (fintelia) [reply src/codecs/webp/extended.rs:342]: Seems `draw_subimage` is actually infallible, so these can't be hit. We should probably refactor that...

**Comment by fintelia** [comment]
The fuzz testing from the CI is showing some issues:
```

failures:

---- codecs::webp::encoder::tests::fuzz_webp_no_panic stdout ----
thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([], 0, 0, 0)
Error: "called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quickcheck-1.0.3/src/tester.rs:165:28


failures:
    codecs::webp::encoder::tests::fuzz_webp_no_panic
```

**Comment by arskov** [comment]
> The fuzz testing from the CI is showing some issues:
> 
> ```
> 
> failures:
> 
> ---- codecs::webp::encoder::tests::fuzz_webp_no_panic stdout ----
> thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
> thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
> thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at 'called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/webp-0.2.4/src/encoder.rs:78:40
> thread 'codecs::webp::encoder::tests::fuzz_webp_no_panic' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ([], 0, 0, 0)
> Error: "called `Result::unwrap()` on an `Err` value: VP8_ENC_ERROR_BAD_DIMENSION"', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quickcheck-1.0.3/src/tester.rs:165:28
> 
> 
> failures:
>     codecs::webp::encoder::tests::fuzz_webp_no_panic
> ```

I tried to run that tests on a master without my changes, and it produces the same errors with the same tests. What would be a suggestion in this case?

**Comment by fintelia** [comment]
Could you grab a backtrace of the failures? (By running with `RUST_BACKTRACE=1`)

If it isn't in the code being changed here, I'd say we just merge this PR and then figure out what's going wrong in a followup.

File: src/codecs/webp/extended.rs [hunk 2]
```diff
@@ -326,10 +326,27 @@ impl ExtendedImage {
...
         match &self.image {
             // will always have at least one frame
-            ExtendedImageData::Animation { frames, .. } => &frames[0].image,
-            ExtendedImageData::Static(image) => image,
+            ExtendedImageData::Animation { frames, anim_info } => {
+                let first_frame = &frames[0];
+                let (canvas_width, canvas_height) = self.dimensions();
+                if canvas_width == first_frame.width && canvas_height == first_frame.height {
+                    first_frame.image.fill_buf(buf);
+                } else {
```
Comment (fintelia) [inline src/codecs/webp/extended.rs:334]: I'm slightly nervous that `first_frame.width` or `first_frame.height` could be larger than the size of the canvas. Do you know what would happen in that case?

**Comment by arskov** [comment]
This is backtrace for tests from master (without the change)
https://gist.github.com/arskov/ef235460456cb29bc65cd25621be03bf

This is backtrace from the branch with the proposal
https://gist.github.com/arskov/df18c28a8c61031e11010e8a28bac3ab

Both show that the panic happens on the line below, so it looks like a separate issue to investigate
https://github.com/image-rs/image/blob/master/src/codecs/webp/encoder.rs#L106

File: src/codecs/webp/extended.rs (hunk 2 above)
Comment (arskov) [reply src/codecs/webp/extended.rs:334]: Good point. If the frame's width or height are larger than the canvas size, or even if they are smaller, but they have an x or y offset + width/height, that gets larger than the canvas width/height, than the code will panic on [extended.rs#L268](https://github.com/image-rs/image/blob/master/src/codecs/webp/extended.rs#L268), because of how Index is implemented for ImageBuffer.

We can make an additional check if the calculated index is within a canvas size [extended.rs#266](https://github.com/image-rs/image/blob/master/src/codecs/webp/extended.rs#L266) and if some x or y is out of bounds, then break the corresponding loop. Some sort of a crop the frame if it is outside the canvas.

Comment (fintelia) [reply src/codecs/webp/extended.rs:334]: If it isn't too much trouble, could you implement that cropping logic now? Otherwise it can wait for a followup PR

Comment (arskov) [reply src/codecs/webp/extended.rs:334]: I created #1960, you can assign it to me. I'll implement it in a separate PR if you don't mind.
