### PR TITLE
Fixed Inconsistent capitalization of Encoder/Decoder structs.

### LINKED ISSUE #1258: Inconsistent capitalization of PNG
https://github.com/image-rs/image/blob/ff6c4d9de05bf71385ca043ab8d67ba66760b70f/src/png.rs

Publicly exposed types `PNGReader`, `PngDecoder`, `PNGEncoder` have inconsistent capitalization.

Changelog entry 0.23.0 suggests that the preferred form in this crate would be `Png`.

### PR DESCRIPTION
**Pull request by ZackJorquera**
fixes #1258 

I created a type definition for each previous struct name and marked them as deprecated. In order to export these typedefs, I needed to use `#[allow(deprecated)]` in some of the `mod.rs` files. Instead, typedef definitions could be in the `mod.rs` files to not have to do this. Or they could be not marked as deprecated. Although, I think the `#[allow(deprecated)]` tags are fine given that the typedefs will be removed in the next version (I assume). 

All the names that were changed:
- `PNGReader` -> `PngReader`
- `PNGEncoder` -> `PngEncoder`
- `BMPEncoder` -> `BmpEncoder`
- `DXTReader` -> `PngReader`
- `DXTEncoder` -> `DxtEncoder`
- `DXTVariant` -> `DxtVariant`
- `gif::Encoder` -> `gif::GifEncoder`
- `ICOEncoder` -> `IcoEncoder`
- `HDRAdapter` -> `HdrAdapter`
- `HDREncoder` -> `HdrEncoder`
- `HDRImageDecoderIterator` -> `HdrImageDecoderIterator`
- `HdrMetadata` -> `HdrMetadata`
- `RGBE8Pixel` -> `Rgbe8Pixel`
- `JPEGEncoder` -> `JpegEncoder`
- `PNMEncoder` -> `PnmEncoder`
- `PNMHeader` -> `PnmHeader`
- `PnmSubtype` -> `PnmSubtype`

### CODE REVIEW

File: src/bmp/mod.rs [hunk 1]
```diff
@@ -8,7 +8,8 @@
 //!
 
 pub use self::decoder::BmpDecoder;
-pub use self::encoder::BMPEncoder;
+#[allow(deprecated)]
+pub use self::encoder::{BmpEncoder, BMPEncoder};
```
Comment (HeroicKatora) [inline src/bmp/mod.rs:12]: Since you commented on this in the description, I think it is perfectly fine to have the attribute ourselves currently.

File: src/dxt.rs [hunk 2]
```diff
@@ -18,7 +18,7 @@ use crate::image::{self, ImageDecoder, ImageDecoderExt, ImageReadBuffer, Progres
 /// Note that DXT2 and DXT4 are left away as they're
 /// just DXT3 and DXT5 with premultiplied alpha
 #[derive(Clone, Copy, Debug, PartialEq, Eq)]
-pub enum DXTVariant {
+pub enum DxtVariant {
```
Comment (HeroicKatora) [inline src/dxt.rs:21]: So have missed something somewhat important in the description of the issue, and sadly did not check this sooner. The ability to use enum variants through type aliases got introduced [in `1.37`](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1370-2019-08-15). Since our MSRV policy is `1.34.2` support this would technically be a breaking change to rename enums. I think we sadly have to keep the orginal names for now for enums, and the alias can have the new capitalization. Clarification: The struct types should be fine.

Comment (ZackJorquera) [reply src/dxt.rs:21]: I completely forgot to change my rustc version, sorry about that.

I can change that.

Comment (ZackJorquera) [reply src/dxt.rs:21]: I also changed `PnmSubtype`. I can fix that too.

Comment (HeroicKatora) [reply src/dxt.rs:21]: Please do, yes. And add a `TODO` comment referencing either the fact or the comment.

File: src/pnm/header.rs [hunk 3]
```diff
@@ -11,8 +11,14 @@ pub enum SampleEncoding {
 }
 
 /// Denotes the category of the magic number
+///
+/// DEPRECATED: The name of this enum will be changed to [`PnmSubtype`].
```
Comment (ZackJorquera) [inline src/pnm/header.rs:15]: I opted to use a comment to say that this was deprecated as it does not require any `#[allow(deprecated)]` tags in the rest of the code.
