### PR TITLE
Issue 1705 dynimage into bytes

### LINKED ISSUE #1705: Panic on AlignmentMismatch when converting dynamic Luma16 image into bytes
This panic happens when using the latest `into_bytes()` method to turn a 16-bit greyscale image into bytes.

## Expected

The test below is expected to pass without panicking.

## Actual behaviour

Instead it panics from unwrapping an error [`bytemuck::PodCastError::AlignmentMismatch`](https://docs.rs/bytemuck/1.9.1/bytemuck/enum.PodCastError.html#variant.AlignmentMismatch).

```none
running 1 test
test can_turn_16bit_image_into_bytes ... FAILED

failures:

---- can_turn_16bit_image_into_bytes stdout ----
thread 'can_turn_16bit_image_into_bytes' panicked at 'called `Result::unwrap()` on an `Err` value: AlignmentMismatch', /home/enet4/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.9.1/src/allocation.rs:143:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
   4: bytemuck::allocation::cast_vec
             at /home/enet4/.cargo/registry/src/github.com-1ecc6299db9ec823/bytemuck-1.9.1/src/allocation.rs:143:3
   5: image::dynimage::DynamicImage::into_bytes
             at /home/enet4/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.2/./src/dynimage.rs:573:43
   6: use_image::can_turn_16bit_image_into_bytes
             at ./src/main.rs:18:26
   7: use_image::can_turn_16bit_image_into_bytes::{{closure}}
             at ./src/main.rs:8:1
```

## Reproduction steps

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a583068769fa6a8ec81135edf9a72634)

```rust
use image::{ImageBuffer, Luma, DynamicImage}; // 0.24

#[test]
fn can_turn_16bit_image_into_bytes() {
    let pixels = vec![65535; 64 * 64];
    let img: ImageBuffer<Luma<u16>, _> = ImageBuffer::from_vec(64, 64, pixels).unwrap();

    let img: DynamicImage = img.into();
    assert!(img.as_luma16().is_some());

    let bytes: Vec<u8> = img.into_bytes();
    assert_eq!(bytes, vec![0xFF; 64 * 64 * 2]);
}
```

This issue does not occur when using the chain `.as_bytes().to_vec()`.

### PR DESCRIPTION
**Pull request by HeroicKatora**
Fixes #1705

### CODE REVIEW

File: src/dynimage.rs [hunk 1]
```diff
@@ -570,9 +570,19 @@ impl DynamicImage {
...
-        ))
+        dynamic_map!(self, |image_buffer| {
+            match bytemuck::allocation::try_cast_vec(image_buffer.into_raw()) {
+                Ok(vec) => vec,
+                Err((_, vec)) => {
+                    // Fallback: vector requires an exact alignment and size match
+                    // Reuse of the allocation as done in the Ok branch only works if the
+                    // underlying container is exactly Vec<u8> (or compatible but that's the only
+                    // alternative at the time of writing).
+                    // In all other cases we must allocated a new vector with the 'same' contents.
```
Comment (Enet4) [inline src/dynimage.rs:581]:
```suggestion
                    // In all other cases we must allocate a new vector with the 'same' contents.
```

**Review by Enet4 — COMMENTED** [review]
Only found a typo. The rest of the changes look sound to me.
