### PR TITLE
Make `huerotate` support any number of channels

### LINKED ISSUE #2859: `huerotate` produces incorrect results for grayscale images.
Obviously, `huerotate` should be a noop for grayscale images, since they have no hue. However, that's not what happens. It will interpret a grayscale pixel `g` as RGB=`[g, 0, 0]` (a red tone), rotate the hue of this color, and then output the R channel of the rotated color.

For grayscale+alpha images, it will interpret `[g, a]` as RGB=`[g, a, 0]`.

## Expected

`huerotate` should output grayscale image unchanged.

## Actual behaviour

See above.

### PR DESCRIPTION
**Pull request by RunDevelopment**
Fixes #2859

I changed the implementations of `huerotate` and `huerotate_in_place` to be a noop for pixels with less than 3 channels. Both will now assume that the first 3 channels are R,G,B (like before) and leave all others untouched (not quite like before). This is done by directly modifying the the first 3 channels of the original pixel, instead of trying to create a new pixel, which previously only supported up to 4 channels.

### CODE REVIEW

File: src/imageops/colorops.rs [hunk 1]
```diff
@@ -224,6 +224,13 @@ where
     P: Pixel<Subpixel = S>,
     S: Primitive,
 {
+    if <I::Pixel as Pixel>::CHANNEL_COUNT < 3 {
+        // ignore grayscale and gray+alpha images
+        // TODO: Find a faster way to convert GenericImageView to ImageBuffer
+        let (width, height) = image.dimensions();
+        return ImageBuffer::from_fn(width, height, |x, y| image.get_pixel(x, y));
```
Comment (197g) [inline src/imageops/colorops.rs]: Re: Find a faster way to convert GenericImageView to ImageBuffer

```suggestion
        let mut buffer = image.buffer_like();
        buffer.copy_from(&image, 0, 0).unwrap();
        buffer
```

Not  only faster but importantly preserves color space attributes.

**Comment by RunDevelopment** [comment]
Done.
