### PR TITLE
Use enlargeable types in to_luma functions.

### LINKED ISSUE #1214: to_luma methods can have floating point issues
In the `rgb_to_luma` and `bgr_to_luma` methods, the floating point arithmetic can result in incorrect results. For example:

```rust
use image::Pixel;

fn main() {
    let pixel = image::Rgb::from([13, 13, 13]);
    
    println!("{:?}", pixel.to_luma()); // Prints `Luma([12])`; should print `Luma([13])`
}
```
This is because in `rgb_to_luma`, `l` is equal to `12.99999904632568359375` before being converted back to a `u8`.

### PR DESCRIPTION
**Pull request by HeroicKatora**
This is an attempt to fix #1214, using the `Enlargeable` trait to
select a suitable type for the calculation in `rgb_to_luma` and
`bgr_to_luma`.

Integer pixel types will use suitable integer pixel types for the
calculation, while floating point pixel types will use floating point
types.

This PR also provides the `Enlargeable` trait for all `Primitive`
types (luckily, `Primitive` is not implemented for 128 bit numeric
types).

The `Color` implementation of all library-defined structs is then
restricted to a subset of Primitive channel types. This is necessary to
allow its conversion operations to utilize the private `Enlargeable`.
Notably however we _relax_ the type itself to not utilize any trait
bound. It's a simple wrapper around an array now.

Rebase of #1215 which was auto-closed due to deleted base branch..

### CODE REVIEW

File: src/traits.rs [hunk 1]
```diff
@@ -70,16 +70,21 @@ declare_primitive!(f64: (0.0)..1.0);
 /// An Enlargable::Larger value should be enough to calculate
 /// the sum (average) of a few hundred or thousand Enlargeable values.
 pub trait Enlargeable: Sized + Bounded + NumCast {
```
Comment (fintelia) [inline src/traits.rs:72]: Could you make this `pub(crate)` for clarity?

Comment (HeroicKatora) [reply src/traits.rs:72]: I'm afraid, no. It's being used in a public interface even though it is not accessible, pretty much like a sealed trait.

**Comment by HeroicKatora** [comment]
@fintelia Other concerns with the public change of this PR? It overlaps with reworking the `Pixel` trait in that if we removed `invert` and color conversion as originally sketched in #1099 then it might be possible to relax this to `Primitive` again.

**Comment by HeroicKatora** [comment]
These are the two API breaking issues still open from `0.24`. We could also do a release just to get it out and then work hard on _actually_ fixing color, with conversion and better buffer API, in a `0.25`.

**Comment by fintelia** [comment]
I think maybe merge this and then roll out a `0.24`? A broader Pixel rework for `0.25` seems reasonable to me.

**Review by fintelia — APPROVED** [review]
