### PR TITLE
Fix setting GIF limits, implement limits for GIF animations

### LINKED ISSUE #1052: Large CPU and memory consumption on decoding a crafted GIF file
Tested on latest git commit as of this writing, ac93e755b51def00c93e7fadd33a5e5593afa1e2

## Actual behavior

Decoding a crafted file mere 469 bytes in size takes over 7 gigabytes of memory. And not just virtual memory - it does get actually used and backed by physical memory.

This sample does not pose a problem as is, but it's possible that by applying the same technique it's possible to create very small files that OOM the system.

## Expected

imagemagick rejects these files immediately. For the exact reason for each file see https://ncry.pt/p/6bPn#OPffqnjbN7RwGKJMwA0BQl3wuNlynKoUxw2dXZx9UKY

## Reproduction steps

Same reproduction code as in #876

I'm attaching all samples classified as hangs by AFL so that you have the most complete info. The file `id:000002,src:000000+000052,op:splice,rep:128` is the most egregious in terms of time and memory consumption.

[image_gif_timeouts.zip](https://github.com/image-rs/image/files/3683273/image_gif_timeouts.zip)

### PR DESCRIPTION
**Pull request by Shnatsel**
1. Fix `.set_limits()` on the GIF decoder to actually set limits
2. Implement limit tracking in the GIF animation decoder, so APIs such as `.into_frames()` now also obey both image size and allocation limits, including for intermediate buffers
3. Add tests to verify limits in animation work correctly, which found (1)

At long last, fixes #1052

### CODE REVIEW

File: src/codecs/gif.rs [hunk 1]
```diff
@@ -58,6 +58,12 @@ impl<R: Read> GifDecoder<R> {
...
 
+        // We previously used `Limits::default()`, but they weren't actually enforced.
+        // Suddenly enabling enforcement while keeping default limits would break existing users.
+        // Therefore, set no limit at least until the next semver break, 0.25.x
+        let mut limits = Limits::default();
+        limits.max_alloc = None;
+
         Ok(GifDecoder {
             reader: decoder.read_info(r).map_err(ImageError::from_decoding)?,
             limits: Limits::default(),
```
Comment (kornelski) [inline src/codecs/gif.rs:69]: should the struct be given the limits variable?

Comment (Shnatsel) [reply src/codecs/gif.rs]: :facepalm: 

Good catch! Done.

**Review by kornelski — APPROVED** [review]

File: src/codecs/gif.rs [hunk 2]
```diff
@@ -58,9 +58,15 @@ impl<R: Read> GifDecoder<R> {
         let mut decoder = gif::DecodeOptions::new();
         decoder.set_color_output(ColorOutput::RGBA);
 
+        // We previously used `Limits::default()`, but they weren't actually enforced.
+        // Suddenly enabling enforcement while keeping default limits would break existing users.
+        // Therefore, set no limit at least until the next semver break, 0.25.x
+        let mut limits = Limits::default();
+        limits.max_alloc = None;
```
Comment (fintelia) [inline src/codecs/gif.rs:65]: I guess we forgot to follow up on https://github.com/image-rs/image/issues/1890, but we should continue the convention defined there of having the `new()` method initialize to `no_limits()` rather than `default()`

Comment (Shnatsel) [reply src/codecs/gif.rs]: I've updated the comments to reflect that and simplified the code a bit. This PR should be good to go.
